### ISSUE TITLE
Uncomment kythe code from the go and Java apis

### ISSUE THREAD

**Issue by ciera** [google/shipshape#101]
We were having significant problems with kythe, as it is not go-gettable right now. Until that is fixed, I had to comment out all references to kythe from our protos and our go code. This will all need to be undone in order to reenable kythe.

**Comment by bzz** [comment]
Is there any known work-in-progress on the Kythe side in order to make it go-gettable?
[Quick search](https://phabricator-dot-kythe-repo.appspot.com/search/query/XKzcnMmsqBhC/#R) over the issue tracker does not reveal much.

**Comment by collinw** [comment]
There is no on-going work to make Shipshape work with Kythe. We are no longer actively working on Shipshape.
