### ISSUE TITLE
ExtendJ analyzer image does not appear to be published anywhere public

### ISSUE THREAD

**Issue by clconway** [google/shipshape#103]
[The ExtendJ analyzer](https://github.com/google/simplecfg) seems to assume that the user will build from source and have a local image to run. Could we push it to some public repository (like [DockerHub](https://docs.docker.com/userguide/dockerrepos/)) so that end users can just use a command like
```
shipshape --analyzer_images="extendj_shipshape/extendj" -categories=ExtendJ ...
```
without cloning the ExtendJ repo, etc.?

**Comment by clconway** [comment]
Got the wrong issue number on fd57cf0. Oops.

**Comment by llbit** [comment]
I have pushed the ExtendJ analyzer plugin to [joqvist/extendj_shipshape](https://hub.docker.com/r/joqvist/extendj_shipshape/) on DockerHub.
