### ISSUE TITLE
"latest" image in our repository

### ISSUE THREAD

**Issue by supertriceratops** [google/shipshape#106]
Attempting to build the container and then run shipshape. It appears the "docker pull" command pulled down a "latest" image from 4 months ago, presumably from our docker images repository.

**Comment by clconway** [comment]
Are you sure that "docker pull" with no version label isn't getting the image from your local repo?

**Comment by supertriceratops** [comment]
I am pretty sure that is not what is happening. To repro:

1) bazel build //shipshape/docker:service
"docker images" now shows an image build a few seconds ago tagged latest for gcr.io/shipshape_releases/service
2) Run the shipshape cli with the argument --tag=latest. Now the image just built has been untagged, and there is a new gcr.io/shipshape_releases/service:latest built 4 months ago.

**Comment by clconway** [comment]
Shouldn't "latest" always implicitly take the newer/more local image? Did we accidentally push an image explicitly labeled "latest" to the repo? Looking at the repo, both "prod" and "staging" are newer than "latest".

**Comment by supertriceratops** [comment]
1) Apparently it does not do this.
2) I am pretty sure someone pushed an image labelled "latest"

**Comment by ciera** [comment]
There are lots of blog posts on the intarwebz dedicated to hatred of "latest" and the fact that it doesn't mean "latest". I've changed our build rules to remove it there. Will now figure out how to remove it from the repo itself.

**Comment by ciera** [comment]
I've deleted the tags from the registry, and also deleted the old "base" image.
