### ISSUE TITLE
Can't run a local version of an external analyzer and prod versions of shipshape

### ISSUE THREAD

**Issue by ciera** [google/shipshape#107]
I thought we had a bug about this, but maybe not.

Right now, we use the --tag=local to determine whether to pull down versions of the services or use the ones build locally (Basically "local" means "Do not even attempt a pull").

However, we don't respect the local tag for external analyzers. This is needed if we want people to be able to test out local versions of their analyzers (like in the tutorial) with prod versions of shipshape.

**Comment by rsamuelklatchko** [comment]
One thing to consider doing as part of this is rethinking LocalKythe as it makes the tag rules more confusing.

**Comment by ciera** [comment]
The entire kythe workflow is going to change a lot later, so I'm not going to worry about this right now. Apparently we're using the wrong docker image, among other things.

**Comment by ciera** [comment]
Fixed by D127
