### ISSUE TITLE
Make a distinction between default and non-default categories

### ISSUE THREAD

**Issue by ciera** [google/shipshape#110]
Right now, all categories for an analyzer run by default when there is no .shipshape file. This means that some analyses, like PostMessage and WordCount, will always be run when they are really intended to be run only when explicitly requested.

I'm turning off PostMessage and WordCount entirely right now. However, instead, we should have GetCategories return two lists: a list of default categories and a list of opt-in analyses.

**Comment by rsamuelklatchko** [comment]
Fixed by https://phabricator-dot-shipshapecode.appspot.com/D170
