### ISSUE TITLE
Long-lived shipshape service can't change directories

### ISSUE THREAD

**Issue by ciera** [google/shipshape#33]
Before starting up, we need to check the volume that is mounted to the shipshape directory. If the files we need to analyzer are not contained within that volume, we need to tear it down and restart it.

We run the risk of always restarting if the user keeps changing which directory they analyze. We could possibly keep multiple copies of the container open in this case. I'm going to start by just restarting when it doesn't match, and we'll see how that works in practice.

**Comment by ciera** [comment]
Test comment. Did any of the other admins get this through a notification email?

**Comment by amshali** [comment]
Not yet resolved for me. Still getting findings from previous runs.

**Comment by collinw** [comment]
@amshali, did you build Shipshape from head, or did you use one of our prebuilt Docker containers?

**Comment by amshali** [comment]
I downloaded it.

**Comment by amshali** [comment]
Any update on this?

**Comment by ciera** [comment]
I'm back from my trips. I thought I had fixed and released this, but emso
says the release hasn't happened in a while. Looking into it.

**Comment by ciera** [comment]
Newest version of shipshape has been released. Try downloading it now.

**Comment by amshali** [comment]
Not fixed.

**Comment by ciera** [comment]
Reopening and assigning to emsod.

Note: I had implemented this by checking to see if the new directory is a subdirectory of the one we already have, and reusing it if possible. Otherwise, it tears down and restarts the container with the correct directory. This logic is somewhat confusing though, so I might have missed a case that amshali is hitting.

You might try instead creating a symlink (in /tmp/shipshape?) and then changing the symlink to point to the desired directory. I don't know if that will actually work (not sure how docker maps the volumes...will it follow the symlink when it maps? Or will it just map to the symlink itself?) It would be a cleaner and more reliable implementation if it works.

**Comment by amshali** [comment]
Looking forward to an actual fix. Thanks!

**Comment by emsod** [comment]
This issue appears to be resolved in the latest release.
