### ISSUE TITLE
How to run a third-party analysis

### ISSUE THREAD

**Issue by mernst** [google/shipshape#36]
At https://github.com/google/shipshape#downloading-and-running-the-cli , would it be possible to give an example of using a third-party analysis?  It's not clear what to pass as the --analyzer_images argument nor how to determine the legal values for the --categories argument.

**Comment by ciera** [comment]
analyzer_images needs to be list of uris to the image; we should provide better documentation and examples for that. Alternately, you can specify them in the .shipshape file.

categories is based on whatever categories the running analyzers have. We should add a CLI option to simply list the currently available categories.

**Comment by mernst** [comment]
Thanks for following up.  The examples, and the CLI option to list categories,would be useful and I look forward to them.

**Comment by emsod** [comment]
We are discussing better workflows for adding third-party analyzers. One thing that is currently standing in the way is the how docker containers are configured with regard to volumes and links to other containers they need. We need to experiment with alternative ways of handling these two things. The directory problem is discussed in https://github.com/google/shipshape/issues/33, and the links problem in https://github.com/google/shipshape/issues/40.

**Comment by ciera** [comment]
You will find a bunch of new docs in shipshape/docs. They are also linked from the main README.md
