### ISSUE TITLE
Replace the cli tests with a go test

### ISSUE THREAD

**Issue by ciera** [google/shipshape#45]
We now have two tests of the CLI written in shell, which just gives me shivers.

Let's actually create a test harness of the CLI in go. We also should add a test for running on a single file, and for the streams mode (if we decide to keep it around).

**Comment by supertriceratops** [comment]
So, it is really nice to have a test that creates the docker images for shipshape and then runs the CLI with the locally created images -- specifically for those (unfortunately frequent) times testing/debugging issues with docker. Will this also be written in go, or stay in shell?

**Comment by ciera** [comment]
My goal was to keep that functionality, but as a go test. It will only be using the locally created images.

**Comment by ciera** [comment]
Migration is now complete, and old tests have been removed.
