### ISSUE TITLE
Investigate latency when using a running service

### ISSUE THREAD

**Issue by ciera** [google/shipshape#68]
amshali reports about a 5 second latency to run, even when analyzing a file in the same directory. We should make sure this is mostly/entirely the analyzer and that there aren't obvious performance problems in shipshape.

**Comment by supertriceratops** [comment]
It looks like when I run shipshape in its default mode on a single .shipshape file it still takes 19seconds.

**Comment by supertriceratops** [comment]
Actually it is just me, it looks like no one else is having these kinds of performance problems. Leaving open since latency could be improved, but downgrading priority.

**Comment by supertriceratops** [comment]
Fixed issues I was having by updating our docker inspect command.

**Comment by ciera** [comment]
Seems to be confirmed for me now. Initial run takes about 5 seconds, subsequent runs are taking 3 seconds.
