### ISSUE TITLE
Switching directories (up) seems to be broken

### ISSUE THREAD

**Issue by ciera** [google/shipshape#72]
Cody attempted to run shipshape using the latest version. He ran it first on kythe/go/platforms and it worked. Then he ran it on kythe/go and it fails because it can't cd into the right directory.

**Comment by collinw** [comment]
This is when running with --stay_up?

**Comment by ciera** [comment]
Yes, which is the default.

**Comment by ciera** [comment]
So, this is now not broken, only because this is restarting the shipshape container every time....

**Comment by supertriceratops** [comment]
How about now?

**Comment by ciera** [comment]
It is broken right now. I already mailed a fix, see D141.
