### ISSUE TITLE
Rerunning the end_to_end test a second time produces no results

### ISSUE THREAD

**Issue by ciera** [google/shipshape#74]
Repro steps:
docker stop shipping_container
docker rm shipping_container
./shipshape/test/end_to_end_test.sh --tag local
./shipshape/test/end_to_end_test.sh --tag local

Notice the difference in output from the last two commands.

**Comment by collinw** [comment]
Does this happen if end_to_end_test.sh is modified to shut down Shipshape after each invocation?

**Comment by ciera** [comment]
Now that we have go tests, I'm going to create a new test that tries to repro this.

**Comment by ciera** [comment]
Test added in D136 and seems to work now. Might have been a problem with the end to end test itself.
