### ISSUE TITLE
end_to_end test in local mode should stop and remove all local containers before proceeding

### ISSUE THREAD

**Issue by ciera** [google/shipshape#75]
Interestingly, when running the end to end test, AndroidLint does believe that it is giving back 9 notes and 0 errors.

LOG_FILE[/tmp/shipshape.android_lint.log]:
-- Starting server endpoint at ":10005"
2015/09/16 23:15:29 called with: shipshape_context: <
  file_path: "TicTacToeLib/AndroidManifest.xml"
  file_path: "TicTacToeLib/LICENSE"
  file_path: "TicTacToeLib/README.google"
  file_path: "TicTacToeLib/README.txt"
  file_path: "TicTacToeLib/_index.html"
  file_path: "TicTacToeLib/default.properties"
  file_path: "TicTacToeLib/res/drawable/lib_bg.9.png"
  file_path: "TicTacToeLib/res/drawable/lib_circle.png"
  file_path: "TicTacToeLib/res/drawable/lib_cross.png"
  file_path: "TicTacToeLib/res/layout/lib_game.xml"
  file_path: "TicTacToeLib/res/layout-land/lib_game.xml"
  file_path: "TicTacToeLib/res/values/strings.xml"
  file_path: "TicTacToeLib/src/com/example/android/tictactoe/library/GameActivity.java"
  file_path: "TicTacToeLib/src/com/example/android/tictactoe/library/GameView.java"
  file_path: "pom.xml"
  file_path: "src/main/java/com/google/shipshape/App.java"
  file_path: "test.js"
  repo_root: "/shipshape-workspace"
>
category: "AndroidLint"
2015/09/16 23:15:29 starting analyzing
2015/09/16 23:15:29 About to run analyzer: AndroidLint
2015/09/16 23:15:33 lint output is ""
2015/09/16 23:15:33 finished analyzing, sending back 9 notes and 0 errors

END[Logs from second CLI run for AndroidLint]
INFO: Checking analyzer results ...
ERROR: Wrong number of ErrorProne results, expected 2, found 0
ERROR: Wrong number of AndroidLint results, expected 8, found 0

**Comment by ciera** [comment]
Ah, never mind. The problem appears to be due to me having an old local container.

Renaming the bug. When running in local mode, we should stop and remove all our containers first.

**Comment by supertriceratops** [comment]
Is this still P1 and not completed?

**Comment by ciera** [comment]
It is now obsolete, as the end to end test has been migrated.
