### ISSUE TITLE
Ensure CI is set up correctly

### ISSUE THREAD

**Issue by ciera** [google/shipshape#87]

**Comment by ciera** [comment]
Also, see if we can get shipshape running on shipshape in the CI

**Comment by clconway** [comment]
Is the idea here to get Travis fixed, or to move off Travis and onto Jenkins?

**Comment by ciera** [comment]
Whatever leaves us with a working CI. We don't currently have travis running shipshape on shipshape, but this might fix that problem.

http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/

**Comment by clconway** [comment]
We don't currently have Travis running at all. :-(
