### ISSUE TITLE
Create a demo repository for showing off shipshape results

### ISSUE THREAD

**Issue by ciera** [google/shipshape#92]

**Comment by clconway** [comment]
We already have a repo for this here:
https://github.com/supertriceratops/experiments

**Comment by ciera** [comment]
Yu Lin has a sample for his analyzer here: http://mir.cs.illinois.edu/~yulin2/CTADetector_sample.tar.gz

**Comment by clconway** [comment]
Added some Go code to supertri's repor here:

**Comment by clconway** [comment]
Copy and paste, GitHub, how does it work?
https://github.com/supertriceratops/experiments/pull/1

**Comment by emsod** [comment]
Moving over to this repo: https://github.com/emsod/experiments

**Comment by supertriceratops** [comment]
We should have a repository owned by "shipshape". I tried to do that with
my experiments repo... Is Collin the only one that is a member of Shipshape?

Cheers,

Caitlin

**Comment by ciera** [comment]
The new demo repo is now up. https://github.com/google/shipshape-demo
