### ISSUE TITLE
Running with no shipshape file should just run everything

### ISSUE THREAD

**Issue by ciera** [google/shipshape#98]
Right now, if you don't have a .shipshape file and run shipshape, you get this:

$ ./shipshape .
E1005 15:34:12.395776   11952 shipshape.go:235] Error making service call: received an error from calling run: service needs to be called with triggered categories and/or a repo root with a valid .shipshape file with the event manual

Instead, it should just run assuming everything is on.

**Comment by supertriceratops** [comment]
Should work now.
